### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by antonvice**
updated wording and used ntgcalls and evgeny mention earlier in the code

### CODE REVIEW

**Comment by Laky-64** [comment]
This PR seems to be AI generated 👀

**Comment by ABG1M** [comment]
@Laky-64 😀

**Comment by antonvice** [comment]
what, the comment or what? I am a native english speaker and looking at the text was disturbing to my eyes, fixed that, and moved references where they looke appropriate

**Comment by Laky-64** [comment]
Why you did this:
[!][NTgCalls](https://github.com/pytgcalls/ntgcalls)

And sounds little bit strange the first line

**Comment by antonvice** [comment]
oops, forgot syntax, here
JUST TRYING TO HELP

**Comment by Laky-64** [comment]
No, wait, don't worry, I actually appreciate it, anyway what do you think of this sentence? "This project allows streaming via Telegram group calls"

**Comment by antonvice** [comment]
@Laky-64 Antonvice is me
The sentence sounds fine, but I think it’s better to say
“The goal/aim of this project is to provide seamless telegram group calls streaming”
Or

.. provide seamless telegram group calls interface

**Pull request closed without merging**
